from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path
from AppSalud import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.mostrar_index, name= 'Home'),
    path('numero_de_turno/', views.mostrar_Numero_de_Turno, name='Numeros_de_Turnos'),
    path('crear_numero_de_turno/', views.crear_Numero_de_Turno, name='Crear_Turno'),
    path('buscar_numero_de_turno/', views.buscar_Numero_de_Turno, name='Buscar_Turno'),
    path('actualizar_numero_de_turno/<turno_id>/', views.actualizar_Numero_de_Turno, name='Actualizar_Turno'),
    path('eliminar_numero_de_turno/<turno_id>/', views.eliminar_numero_de_turno, name='Eliminar_Turno'),
    path('medicos/', views.mostrar_medicos, name='Medicos'),
    path('crear_medico/',views.crear_Medico, name='Crear_Medico'),
    path('buscar_nombre_medico/', views.buscar_nombre_medico, name='Buscar_nombre_medico'),
    path('actualizar_medico/<medico_id>/', views.actualizar_Medico, name='Actualizar_Medico'),
    path('eliminar_medico/<medico_id>/', views.eliminar_medico, name='Eliminar_Medico'),
    path('matricula/', views.mostrar_matricula, name='Matricula'),
    path('crear_matricula/', views.crear_Matricula, name='Crear_Matricula'),
    path('buscar_numero_matricula/', views.buscar_numero_matricula, name='Buscar_numero_matricula'),
    path('actualizar_matricula/<matricula_id>/', views.actualizar_Matricula, name='Actualizar_Matricula'),
    path('eliminar_matricula/<matricula_id>/', views.eliminar_matricula, name='Eliminar_Matricula'),
    path('coberturas/', views.mostrar_coberturas, name='Coberturas'),
    path('crear_coberturas/',views.crear_coberturas,name="Crear_Coberturas"),
    path('buscar_coberturas/',views.buscar_nombre_cobertura,name="Buscar_Coberturas"),
    path('actualizar_coberturas/<int:id_cobertura>/',views.actualizar_coberturas,name="Actualizar_Coberturas"),
    path('eliminar_coberturas/<int:id_cobertura>/',views.eliminar_coberturas,name="Eliminar_Coberturas"),
    path('especialidades/',views.mostrar_especialidades,name="Especialidades"),
    path('crear_especialidades/',views.crear_especialidades,name="Crear_Especialidades"),
    path('buscar_especialidades/',views.buscar_nombre_especialidad,name="Buscar_Especialidades"),
    path('actualizar_especialidades/<int:id_especialidad>/',views.actualizar_especialidades,name="Actualizar_Especialidades"),
    path('eliminar_especialidades/<int:id_especialidad>/',views.eliminar_especialidades,name="Eliminar_Especialidades"),
    path('localidades/',views.mostrar_localidades,name="Localidades"),
    path('crear_localidades/',views.crear_localidades,name="Crear_Localidades"),
    path('buscar_localidades/',views.buscar_nombre_localidad,name="Buscar_Localidad"),
    path('actualizar_localidades/<int:id_localidad>/',views.actualizar_localidades,name="Actualizar_Localidad"),
    path('eliminar_localidades/<int:id_localidad>/',views.eliminar_localidades,name="Eliminar_Localidad"),
    path('paciente/',views.mostrar_Pacientes,name="Pacientes"),
    path('crear_pacientes/', views.crear_pacientes, name='crear_paciente'),
    path('buscar_nombre_paciente/', views.buscar_nombre_Pacientes, name='Buscar_Paciente'),
    path('actualizar_paciente/<paciente_id>/', views.actualizar_paciente, name='Actualizar_Paciente'),
    path('eliminar_paciente/<paciente_id>/', views.eliminar_paciente, name='Eliminar_Paciente'),
    #path('prepagas/',views.mostrar_prepagas,name="Prepagas"),
    #path('crear_prepaga/',views.crear_prepaga,name="Crear_Prepaga"),
    #path('buscar_prepaga/',views.buscar_nombre_prepaga,name="Buscar_Prepaga"),
    #path('actualizar_prepaga/<nombre_prepaga>/',views.actualizar_prepaga,name="Actualizar_Prepaga"),
    #path('eliminar_prepaga/<nombre_prepaga>/',views.eliminar_prepaga,name="Eliminar_Prepaga"),
    path('sedesclinicas/',views.mostrar_sede_clinica,name="Sedesclinicas"),
    path('crear_sede/', views.crear_sede, name='Crear_Sede'),
    path('buscar_sede/', views.buscar_sede, name="Buscar_Sede"),
    path('actualizar_sede/<int:id_sede>/', views.actualizar_sede, name='Actualizar_Sede'),
    path('eliminar_sede/<int:id_sede>//', views.eliminar_sede, name='Eliminar_Sede'),
    path('registro/', views.registro_usuario, name='Registro'),
    path('login/', views.login_request, name='Login'),
    path('logout/', views.logout_request, name='Logout'),
]
