# Generated by Django 5.1.2 on 2024-10-26 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSalud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobertura',
            name='id_obra_social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppSalud.obra_social'),
        ),
        migrations.AlterField(
            model_name='cobertura',
            name='id_prepaga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppSalud.prepaga'),
        ),
        migrations.AlterField(
            model_name='cobertura',
            name='id_sin_cobertura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppSalud.sin_cobertura'),
        ),
    ]
