# Generated by Django 5.1.2 on 2024-10-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSalud', '0003_cobertura_nombre_cobertura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobertura',
            name='id_obra_social',
        ),
        migrations.RemoveField(
            model_name='cobertura',
            name='id_prepaga',
        ),
        migrations.RemoveField(
            model_name='cobertura',
            name='id_sin_cobertura',
        ),
    ]
