# Generated by Django 5.1.2 on 2024-10-26 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id_numero', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especialidad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=30)),
                ('provincia', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_legajo', models.IntegerField(max_length=30)),
                ('años_de_servicio', models.IntegerField(max_length=10)),
                ('pacientes_atendidos', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Metodo_de_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_de_pago', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Obra_Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_obra_social', models.CharField(max_length=30)),
                ('plan', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Prepaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prepaga', models.CharField(max_length=30)),
                ('plan', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_obra_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSalud.obra_social')),
                ('id_prepaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSalud.prepaga')),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id_dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_paciente', models.CharField(max_length=30)),
                ('apellido_paciente', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo_paciente', models.CharField(max_length=30)),
                ('id_cobertura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSalud.cobertura')),
                ('id_localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSalud.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Sede_Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_sede', models.IntegerField(max_length=30)),
                ('direccion_sede', models.CharField(max_length=30)),
                ('email_sede', models.EmailField(max_length=254)),
                ('id_localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSalud.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Numero_de_Turno',
            fields=[
                ('id_turno', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('id_numero_de_consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSalud.consultorio')),
                ('id_dni_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSalud.pacientes')),
                ('id_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSalud.sede_clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medico', models.CharField(max_length=30)),
                ('apellido_medico', models.CharField(max_length=30)),
                ('dni_medico', models.IntegerField(max_length=30)),
                ('id_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSalud.especialidad')),
                ('id_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSalud.matricula')),
                ('id_numero_de_consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSalud.consultorio')),
                ('id_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSalud.sede_clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Sin_Cobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('id_metodo_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSalud.metodo_de_pago')),
            ],
        ),
        migrations.AddField(
            model_name='cobertura',
            name='id_sin_cobertura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSalud.sin_cobertura'),
        ),
        migrations.CreateModel(
            name='Sistema_de_Turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dni_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSalud.pacientes')),
                ('id_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSalud.especialidad')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSalud.medicos')),
                ('id_numero_de_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSalud.numero_de_turno')),
            ],
        ),
    ]
